# Generated by Django 3.2.25 on 2025-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='Rupee', max_length=20),
        ),
    ]
